title: "Manish Chaudhari"
email: "manish4u14@gmail.com"
description: >-
  Senior Business Analyst | AI Integration | Web Application Expert
baseurl: ""
url: "https://manish4u14-utexas.github.io"
github_username: manish4u14-utexas

theme: jekyll-theme-minimal

linkedin_username: mkchaudhari
show_downloads: true